@echo off
echo Démarrage de Minikube...
minikube start --driver=docker
echo Chargement des images...
minikube image load backend:latest
minikube image load frontend:latest
echo Déploiement de l'application...
kubectl apply -f k8s/
echo.
echo Application prête ! Ouverture automatique...
minikube service frontend --url
pause